services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=learning_platform'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=platform_user'
    ports:
      - '5432:5432'
